services:
  gift:
    image: mollen/gift-service
    build:
      context: .
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}


  postgres:
    image: postgres:17
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}

    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${PG_DB}
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5


volumes:
  postgres_data: